### ISSUE TITLE
Allow setting important at the utility level

### ISSUE THREAD

**Issue by conormuirhead** [ThinkUniform/uniformcss#15]
**Is your feature request related to a problem? Please describe.**
When using the a gutter utility class like `gutter-y-16` to apply spacing between child items, there are time when overriding the spacing of a single element is necessary. Of course there's always the option to remove `.gutter-y-16` and instead apply custom margins to all the child elements — this can be annoying though when all but one are the same value. It'd be really nice if there was a way to use a margin utility like `mt-24` to override the margin on the one outlier in a group.

The problem today is that because of specificity, the `.gutter-y-16 > * + *` selector will always win over `.mt-24`.

**Describe the solution you'd like**
One option to address this situation could be to allow making some utilities use `!important` while allowing most to still go without it. For example, if all the margin utilities could be set to `important: true` that would allow me to override gutter margins for exceptions as they come up. Additionally, due to the nature of margin utilities there isn't really much risk in using `!important` as they're highly unlikely to collide in any unexpected ways.

**Describe alternatives you've considered**
Alternatives in my mind include:
- Using `gap` + `flex`/`flex-column` utilities instead of `gutter`. With flex + gap you can use margin utilities to add extra space or negative margin utilities to cancel out gaps as needed. I think this is the best alternative, though technically browser support isn't quite fully there yet. Additionally, applying `flex` does impact the width of child elements unless you add extra classes.
- When there is an exception, just remove `gutter` and manually space all the individual items
- Adding the ability to make some utilities (like margin) use `!important` without doing it for all

**Comment by jinsupark** [comment]
New Uniform CSS v1.2.0 now supports localized important setting!

[Read the announcement here](https://github.com/ThinkUniform/uniformcss/discussions/19)

**Comment by conormuirhead** [comment]
Thanks for the localized important support @jinsupark!

I just tried it out and noticed that it does seem to generate important statements for pseudos, but not for the responsive classes. Without the responsive classes getting `!important` too they won't work. Is there an easy fix for that?

**Comment by jinsupark** [comment]
Just pushed the fix for this 🚀
