### ISSUE TITLE
Custom delimiters in documentation

### ISSUE THREAD

**Issue by conormuirhead** [ThinkUniform/uniformcss#16]
**Is your feature request related to a problem? Please describe.**
The project documentation is nice and helpful! But...when you use custom delimiters for your project, it can make using the docs challenging since the class values and such don't match what you're using in your own codebase. This is especially true for folks that are new to the system.

**Describe the solution you'd like**
It'd be super helpful if there was a way to enter your custom delimiters into the documentation site, similar to choosing a language. After entering those, the docs could show the appropriate delimiters across examples and such — it'd be really helpful. The same problem exists for other configurable aspects like colors, spacing scales, etc. but it seems like the basic syntax of the selectors is probably the area that might be most impactful.

**Describe alternatives you've considered**
Other alternatives I've considered, is making some way to auto-generate documentation within a project, based on the project's configuration. Like what if there was autocomplete available that mapped to your configuration of the system.

**Comment by jinsupark** [comment]
Good news! Thanks to the feedback you gave this week, I've gone ahead and implemented JSON output-mode like we talked about in version 1.2.0 please check it out!

[Read the announcement here](https://github.com/ThinkUniform/uniformcss/discussions/19)

### How it works

**INPUT**
```scss
@use "uniform" as * with (
  $config: (
    output-mode: 'json',
    excludes: (all),
    includes: (text-align)
  )
);
```

**OUTPUT**
```
{
  "text-align": {
    "selector": ".text-justify",
    "extra-selector": "",
    "important": "false",
    "responsive": "true",
    "pseudos": "none",
    "properties": {
      "text-align": "justify"
    }
  }
}
```

**Comment by jinsupark** [comment]
I understand It would be great to allow the docs to auto-generate based on the JSON outputted. This is not currently implemented but is now very high on the list! I will update you regarding this soon!

The JSON output was the first step in making this a reality, now that's done perhaps UniformDocs is just around the corner 😉

**Comment by conormuirhead** [comment]
This is a fantastic change. And also opens the door to creating internal tools that would be helpful. Thank you!
