### ISSUE TITLE
Parity with tailwind

### ISSUE THREAD

**Issue by aolko** [ThinkUniform/uniformcss#2]
How close this frameworks gets to tailwind? For example, i can't see both flex "grids" and grids in the docs.

**Comment by jinsupark** [comment]
Like Tailwind, Uniform is a utility-first CSS framework. The biggest difference is that Tailwind is built with JS whereas Uniform is built completely in Sass, therefore, the way you set up and configure is very different. The utility class name for each CSS property, however, is very similar between the two frameworks.

**Comment by aolko** [comment]
Sure, but will you port over all the tailwind's components? Also props for quick response.

**Comment by jinsupark** [comment]
Our current goal is to focus on building a productive utility-first workflow for Sass and less about comparing ourselves to Tailwind, however, you will find that most if not all of the core CSS properties are supported including specialized ones such as `background-opacity`, `space-between`, and `aspect-ratio`.

If it's helpful to have a side-by-side comparison of each utility, I'll look into sharing this in a form of a blog post at some point in the near future! 👍
