### ISSUE TITLE
Checked sibling pseudo

### ISSUE THREAD

**Issue by conormuirhead** [ThinkUniform/uniformcss#20]
**Is your feature request related to a problem? Please describe.**
So sometimes you have a radio set in a form that you want to treat more visually, rather than with plain radio buttons. A common CSS pattern for this situation is to wrap the radio inputs with `label` elements — so they can still be check via clicking — and then to use a `:checked +` or `:checked ~`  sibling selector to style the more visual representation when its accompanying radio is checked. Here's an example:

<img width="329" alt="image" src="https://user-images.githubusercontent.com/438031/147121674-9f28f510-3988-480f-a8b1-f8aaae51ea6f.png">

**Describe the solution you'd like**
Similar in spirit to the `group-hover` pseudos, it'd be neat to be able to have some sort of `checked-sibling` pseudo that you could use for situations like this. For that example above, I could imagine using it to apply the blue border when the sibling radio was checked. Something like:

```
<img src="..." class="shadow-sm border-2 border-transparent checked-sibling.border-blue" />
```

And the resulting CSS would look like:

```
:checked ~ .checked-sibling\.border-blue {
  --border-opacity: 1;
  border-color: rgba(var(--blue), var(--border-opacity));
}
```

**Describe alternatives you've considered**
I haven't been able to come up with any alternatives to this kind of pseudo that don't require me to either write some javascript behavior or some custom CSS. I'll probably end up implementing this with visible radios for now since I'm trying to go as far as possible without custom CSS.

**Comment by jinsupark** [comment]
I think the solution you have provided is very sound. I have implemented checked sibling support. You can enable this for each utility using `checked-sibling` now in v1.3.0 @conormuirhead

**Comment by conormuirhead** [comment]
Thanks!
