### ISSUE TITLE
List style positions has a typo

### ISSUE THREAD

**Issue by conormuirhead** [ThinkUniform/uniformcss#21]
**Describe the bug**
Looks like a typo snuck in by pluralizing `list-style-position` to `list-style-positions`. You can see [the property name on MDN here](http://developer.mozilla.org/en-US/docs/Web/CSS/list-style-position) is `list-style-position`. But in `/utilities/typography/core-list-style-position.scss` [it uses a pluralized form](https://github.com/ThinkUniform/uniformcss/blob/7d3384ca8a7c6af3cc4c5a7ca11c36ac421ea74c/uniform/utilities/typography/core-list-style-position.scss#L12): `list-style-position`.

Ultimately this results in browsers not rendering the style, because the property is unrecognized.

**To Reproduce**
1. Add a list style position utility class like `list:outside` to an element
2. Open web inspector on that element
3. See that the style isn't applied because it isn't recognized

---

Sidenote: @jinsupark for something like this would you prefer that I open a pull request or something instead? I haven't contributed to a project like this before, so it'd be helpful to understand your preferred process.

**Comment by jinsupark** [comment]
Hey @conormuirhead thanks for discovering this! I will push the fix for this right away.

Alternatively yes if you could submit a push request that would also be super helpful!

Thanks!
