### ISSUE TITLE
Allow opting out of semantic colors

### ISSUE THREAD

**Issue by conormuirhead** [ThinkUniform/uniformcss#24]
I'm not seeing a way to opt out of Uniform's semantic colors like "success", "info", etc. And there also doesn't seem to be a way to override the default values within the config file. I would expect to be able to exclude these altogether via theme config, and likewise to be able to extend them as I do with all the other colors — though I personally only need the exclusion right now.

Without this, I'm left to write custom CSS to override the custom properties, which is less than ideal as I want to keep as much of this as possible within generated CSS via config. Additionally, when we can't exclude these it means they're present in our generated CSS and JSON (which we use for documentation), which isn't good since in our project we'd prefer to just use literal color names like `green` instead of `success`, so really we just don't want them present at all.

What do you think @jinsupark, possible to add a config option for excluding the semantic color utilities?

**Comment by jinsupark** [comment]
Hey @conormuirhead, internally we have found ourselves not using both the semantic and secondary colors either. It was a nice idea at first, however, we soon found ourselves not needing it in any part of our UI.

In **version v1.4.0** we have removed secondary and semantic colors from the default configuration setup.

**Comment by conormuirhead** [comment]
Good to know that we felt similarly in our usage. Thanks for the quick update!
