### ISSUE TITLE
Please add instructions for Vite

### ISSUE THREAD

**Issue by djmtype** [ThinkUniform/uniformcss#25]
I couldn't figure out how to set this up with Vite via npm after I installed it. Vite couldn't find the scss file to import.

So, instead, I ended up cloning the repo, thinking this would work: 

```scss
// main.scss
@use 'uniformcss/uniform' as *;
```

This resulted in errors. 

```
Error: Can't find stylesheet to import.
  ╷
1 │ @forward "uniform/core";
```

Finally, I just moved **uniform** directory out of **uniformcss** directory. 

This worked, but it's not ideal. 
```scss
// main.scss
@use 'uniform' as *;
```

**Comment by djmtype** [comment]
BTW, this seems to work when installed with npm. 

`@use './node_modules/uniformcss/uniform' as *;`

**Comment by conormuirhead** [comment]
Sounds like you probably need to look into the load paths for you SASS setup: https://sass-lang.com/documentation/at-rules/use#finding-the-module

**Comment by kjvdven** [comment]
I managed to fix this in my parceljs setup with a `.sassrc` file.

```
{
  "includePaths": [
    "./node_modules/uniformcss"
  ]
}
```

This makes it work with the following `main.scss`
```
// main.scss
@use "node_modules/uniformcss/uniform" as * with (
  $config: (
    // remove default colors
    colors: null,

    // remove negative sizes
    // negative-sizes: null,
    
    // exclude the following properties from build
    excludes: (background, background-attachment, opacity),
  )
);
```

I have to comment out the `negative-sizes`, because that also breaks the build.

**Comment by jinsupark** [comment]
As @conormuirhead has mentioned, depending on your Sass build setup, the load paths must be correctly configured to allow Sass to know where all the external paths are located: https://sass-lang.com/documentation/at-rules/use#finding-the-module

Once load paths are setup, you can simply included `@use 'uniform' as *` and it should compile with no other changes required.

**Comment by jinsupark** [comment]
Thanks for this tip @kjvdven, just fyi when setting up your `.sassrc` in that way, you don't need to include the full path, you can simply write: `@use 'uniform' as *` and it should compile correctly.

**Comment by jinsupark** [comment]
@kjvdven the latest version https://github.com/ThinkUniform/uniformcss/releases/tag/1.5.2 now supports passing in `null` value to the negative/positive sizes in configuration 👍 .
