### ISSUE TITLE
Typo in letter-spacing docs

### ISSUE THREAD

**Issue by stillingdesign** [ThinkUniform/uniformcss#26]
**Describe the bug**
There are a couple typos on the letter-spacing / tracking docs.

**To Reproduce**
1. Go to 'https://uniformcss.com/cheatsheet/letter-spacings/#visual-reference'

**Expected behavior**
Correct labeling:
`tracking-tightest`
`tracking-tighter`
`tracking-tight`

**Screenshots**
<img width="995" alt="Screen Shot 2022-03-24 at 1 32 12 PM" src="https://user-images.githubusercontent.com/66682227/159986685-a6ee19fa-941d-4fd8-82c0-8b6160e93040.png">

**Desktop (please complete the following information):**
 - OS: `macOS`
 - Browser `chrome`
 - Version `Version 99.0.4844.83 (Official Build) (arm64)`

**Comment by conormuirhead** [comment]
@jinsupark this seems like a nice opportunity to introduce you to @stillingdesign, he handles all the marketing design over here at Rewatch, and he's currently working on bringing Uniform into our marketing site since it's worked so well in the product.

**Comment by jinsupark** [comment]
Thanks for making the intro @conormuirhead I'm delighted to hear Uniform is adding value to your product! Thank you  @stillingdesign I will update the docs (new docs coming soon, more details below).

We have some very exciting new things coming up for Uniform this year:
- Uniform Icons
- Uniform UI/Plugins
- New open-source docs site that can be used to auto-glossary glossary from exported JSON

Looking forward to sharing more with you soon, thanks again for believing in this project!

**Comment by jinsupark** [comment]
If you have any questions regarding bringing this to your marketing website, please let me know. Happy to jump on a call.

**Comment by stillingdesign** [comment]
@jinsupark thank you and will do! I'm excited for the new things you mentioned. I haven't worked with a tool like uniform before, it's super slick!!!

**Comment by jinsupark** [comment]
Transitioning back from paternity leave, thanks again for finding this. Fix is now live!
