### ISSUE TITLE
Easily swap out padding-based ratio for native aspect-ratio

### ISSUE THREAD

**Issue by stillingdesign** [ThinkUniform/uniformcss#27]
**Is your feature request related to a problem? Please describe.**
Recently, I attempted to swap out the default `ratio` that uses padding for a custom `ratio` utility that uses `aspect-ratio` instead. It was a bit complex to do since ratio is a special utility.

**Describe the solution you'd like**
It depends, I am curious how often people prefer using the padding approach versus the new native `aspect-ratio` approach to do this sort of stuff?

If keeping the padding approach, I would suggest making `ratio` overridable in the theme settings.

If the padding approach was implemented prior to css `aspect-ratio` and no longer is relevant - I would recommend replacing padding/height with the new `aspect-ratio` property.

**Additional context**
Currently, I am using aspect-ratio to uniformly and exactly size various images and videos on a blog. Both methods work, `aspect-ratio` is just a lot easier to work with in varying layouts.

**Comment by jinsupark** [comment]
Hey @stillingdesign the native css approach is of course always most preferable and the the current `padding` approach will be replaced with the native `aspect-ratio` in the next major version of Uniform CSS.

In the meantime, you can edit the existing `extension-ratio.scss` or pass in the following into your config to achieve native CSS aspect-ratio utilities:

```scss
@use 'uniform' as * with (
  $config: (
    utilities: (
      aspect-ratio: (
        important: false,
        shorthand: ratio,
        responsive: true,
        responsive-pseudos: false,
        extra-selector: null,
        properties: (
          aspect-ratio,
        ),
        static-properties: (),
        variants: (
          square: '1 / 1',
          '16-9': '16 / 9',
          '4-3': '4 / 3',
          '2-1': '2 / 1',
          '16-10': '16 / 10',
          '9-16': '9 / 16',
          '3-4': '3 / 4',
          '1-2': '1 / 2',
          '10-16': '10 / 16',
        ),
        pseudos: (
          none,
        ),
      ),
    ),
    excludes: (
      all,
    ),
    includes: (
      aspect-ratio,
    ),
  )
);
```

**Comment by stillingdesign** [comment]
It does, thank you @jinsupark !
