### ISSUE TITLE
Consider generating `auto` variants where appropriate

### ISSUE THREAD

**Issue by michaellenaghan** [ThinkUniform/uniformcss#29]
Consider generating `auto` variants where appropriate — e.g., `mx-auto`, for old-style centering.

To be clear, it's already easy to get the generator to produce them, e.g.:

```scss
@use "uniform" as * with (
  $config: (
    utility: (
        margin-x: (
            extend: (
                variants: (
                    auto: auto
                )
            ),
        ),
    ),
  )
);
```

It might just be a better out-of-the-box experience if they're already there. 

(I ran into this as soon as I started trying to markup an existing page.)

**Comment by jinsupark** [comment]
I do need to however update the API reference to reflect this. The new docs site will go live taking advantage of the JSON output solution https://uniformcss.com/docs/build-settings/#advanced-settings so the reference will all be completely accurate and up to date.

**Comment by michaellenaghan** [comment]
Hey, I know this is closed but as far as this comment goes:

> FYI it should be utilities not utility

it turns out I got that from the docs; look at the example [here](https://uniformcss.com/docs/utilities-settings/#disabling-defaults). (I was looking for an example with `extend` and that was the first one I found.)
