### ISSUE TITLE
Consider making `@include apply("")` do nothing, rather than producing an error

### ISSUE THREAD

**Issue by michaellenaghan** [ThinkUniform/uniformcss#32]
This is a small convenience thing, but it would be nice if:

```scss
.some-class {
    @include apply("");
}
```

did nothing rather than producing an error.

(In the process I'll describe later on today, I added classes to my HTML, and then added the classes to my CSS, and then started styling the classes. When I added the classes I added empty `apply`s — but apparently you can't do that today. As I said: just a small convenience thing.)

**Comment by jinsupark** [comment]
Hey, @michaellenaghan thanks! This is a very easy change so happy to provide some extra convenience 👍
https://github.com/ThinkUniform/uniformcss/releases/tag/1.5.3
