### ISSUE TITLE
Consider a cohesive responsive scaling strategy

### ISSUE THREAD

**Issue by michaellenaghan** [ThinkUniform/uniformcss#33]
To be clear: the framework will allow me to do exactly what I want to do. Everything that follows is just about improving the out-of-box experience.

===

It's taken me some time to work out a good responsive sizing strategy in UniformCSS. I think there are three main issues:

* [Some things](https://uniformcss.com/cheatsheet/font-sizes/) are "t-shirt" sized; [others](https://uniformcss.com/cheatsheet/sizing-scales/) are not.

* The t-shirt sized things don't scale responsively the way you might expect.

* The not-t-shirt sized things are *defined* in terms of `rem`s (e.g., `0.625rem`), but *labelled* in terms of pixels (e.g. `size-10`).

The first issue means that it takes some time and effort to work out a correspondence between the two kinds of scales — especially at different breakpoints. Not at all unusual, but perhaps unnecessary friction.

The second issue is easier to illustrate with an example.

To begin with, I wanted 18px font sizes on phones and 20px font sizes on desktops. Here's one way to get that:

```scss
body {
    @include apply("text-lg sm.text-xl");
}
```

And then, looking at the scales, I decided that I wanted a 7xl `h1` size on desktops, and "something smaller" on phones. So:

```scss
h1 {
    @include apply("text-6xl sm.text-7xl");
}
```

That seems like it works. If you do the math, though, you'll see that I haven't just changed the size, I've also changed the ratio:

* `text-lg` = 18px, `text-6xl` = 40px, 18:40 = 1:2.2
* `text-xl` = 20px, `text-7xl` = 48px, 20:48 = 1:2.4

Not fatal, but not intended either. More importantly, if I'm trying to come up with a general solution to responsive sizing, I better not take that approach to re-sizing *space*, where changing proportions are more likely to be visible. (Think about something that has a 2:1 horizontal-to-vertical padding ratio — and then doesn't.)

What I would generally do — though not all CSS frameworks are very happy about this — is to base everything in `rem`s, and scale my root font size at different breakpoints. Obviously that simplifies almost everything, e.g.:

```scss
h1 {
    @include apply("text-6xl");
}

body {
    @include apply("text-md");
}
```

and pushes responsive re-sizing into `html`. (It can also introduce new problems, but for the kinds of work I do these days it's usually a better starting point; there's less tweaking to do.)

The reason I didn't do that right away was the third issue. :-) I was already expending mental effort because the non-t-shirt sizes (e.g., `size-10`) were defined in terms of `rem`s, and those `rem`s were different from my `body` font sizes on phone and desktop. (That's an issue because, for example, I'd like to add `rem`-based bottom margins to `h1`, `p`, etc.) But even worse: they were labelled in pixels even though they were defined in `rem`s. Thinking about all of those things at the same time exceeded my mental load limit!

===

Here are a few general suggestions:

 * Consider supporting both t-shirt sizes and non-t-shirt sizes where appropriate (e.g., maybe add non-t-shirt sizes to fonts, maybe add t-shirt sizes to sizings?); in my head, users would choose one approach or the other
 * Consider how t-shirt sizes scale — ideally, in a user-configurable way (minor third, major third, etc.)
 * Consider how t-shirt sizes re-size at different breakpoints (so that the scale is preserved)
 * Consider labelling `rem`s as `rem`s

To be clear: I'm not saying that all of those things must be done for any of this to be usable. Rather, I'm saying that there should be one cohesive story out of the box. If there's choice, all the better. But at least one.

Btw, it's very possible that you had a model in mind that just didn't occur to me (or I missed it in the docs). If so, please let me know!

===

As I said, everything I want to do I can. All of this is just about the out-of-box experience.

Here's what I'm going to try today:

 * I'm going to change the root font size at different breakpoints (default 18px, and 20px above `sm`)
 * I'm going to re-define the t-shirt sizing using a well-known scale (mostly just so that I can have a mental model of *how* things are scaling)
 * I'm going to add t-shirt sizing to the sizing module

I'll see how that goes.

**Comment by michaellenaghan** [comment]
Seems to all work as expected. The configuration looks something like this:

```scss
@use "uniform" as * with (
  $config: (
    ...
    font-sizes: (
      ...
      sm: (
        font-size: 0.800rem,
        line-height: 1.75,
      ),
      md: (
        font-size: 1.000rem,
        line-height: 1.75,
      ),
      lg: (
        font-size: 1.250rem,
        line-height: 1.625,
      ),
      ...
    ),
    negative-sizes: (
      ...
      nsm: -0.800rem,
      nmd: -1.000rem,
      nlg: -1.250rem,
      ...
    ),
    positive-sizes: (
      ...
      sm: 0.800rem,
      md: 1.000rem,
      lg: 1.250rem,
      ...
    ),
    radiuses: (
      ...
      sm: 0.375rem,
      md: 0.500rem,
      lg: 0.750rem,
      ...
    ),
    ...
  )
);
```

Responsiveness comes from the root element:

```scss
html {
  font-size: 18px;
  @include screen(sm) {
    font-size: 20px;
  }
}
```

Everything else is simple:

```scss
...
body {
    @include apply("text-md");
}
...
h1 {
    @include apply("text-2xl");
}
h2 {
    @include apply("text-xl");
}
h3 {
    @include apply("text-lg");
}
...
```

Margins and padding are also t-shirt sized using the same scale; you can see that in the configuration. (I may need to tweak something at some point, but I haven't had to so far.)

One wrinkle to be aware of is that the `rem` function hard-codes an assumption of 16px [here](https://github.com/ThinkUniform/uniformcss/blob/5c8c87927a00c4121051e766b5fb56147c2b71c8/uniform/core/_index.scss#L23), so you shouldn't use it if you're using this approach.

**Comment by jinsupark** [comment]
I have definitely explored utilizing global rem adjustments to handle the responsiveness of fonts and sizing in the past. 

In an ideal world, I would love to be able to simply apply the golden ratio similar to font scaling seen in https://www.gridlover.net/ however often times I have found translating designs across different devices don't always follow this rule as elegantly as I'd like. Sometimes the font size is too small or big when taking this approach and further micro-adjustments are needed.

This is why I've personally opted for the hard declarative approach to be flexible and unopinionated in order to stay closer to the nature of utilities (do one thing well).

There is some unit discrepancy between w-20 (20px) being converted to rems, however, the current most popular and recommended unit for sizing things is still rems so I don't think that will change anytime soon.

However, if you do prefer to scale font-sizing using the more semantic t-shirt approach I think the workaround configuration example above seems like the perfect solution!

**Comment by michaellenaghan** [comment]
I think we may be slightly cross-purposes; I could be misreading, but it seems like you think I advocated for things I don't think I advocated for.

Let me focus on what I think is the single most important point:

 * Sizes are using pixel-based labels (e.g., `w-20`), but rem-based definitions (`1.25rem`). I suggest making the labels match the units — both pixels, or both rems.
 
I'd prefer rems, but the key point is that I think they should match.

If you change your base font size to, say, 18px, `w-20` is actually 22.5px. That is... rather confusing.

(Another option would be to make the labels "unitless." That's what you do with your font sizes, by using t-shirt sizes.)

I'll pick up on another point in another reply.

(If you know what I meant but disagree, no problem; I just want to make sure that we agree about what we disagree about. :-)

**Comment by conormuirhead** [comment]
FWIW, I've very much enjoyed that (assuming the 16px baseline) I can just think in px units for widths, margins, etc. and know that it's handled via rem units behind the scenes. In the past I have found t-shirt sizes to be an unhelpful abstraction when it comes to spacing and sizing. And having to think in rem fractions all the time sounds like it'd require me to constantly be doing math.

My feeling is that when using Uniform you should avoid changing your base font, and instead if you want a default font size of 18px for all your text, apply that at a high-level wrapping container like the `<main>` element so you can continue to enjoy the simplicity of pixel unit thinking in those size & space utility classes.

**Comment by michaellenaghan** [comment]
My overall point was that I thought there should be *some* consistent story to responsive scaling.

Today you might do something like this:

```html
    <h1 class="font-5xl sm.font-6xl md.font-7xl lg.font-8xl">
        Lorem ipsum
    </h1>
    <p class="md sm.lg md.xl lg.2xl">
        Lorem ipsum...
    </p>
    <button class="px-20 py-18 sm.px-24 sm.py-20 md.px-28 md.py-24 lg.px-32 lg.py-28">
        Lorem ipsum
    </button>
```

Here are the body-to-heading ratios at each breakpoint:

 * default: 1rem:2.25rem = 2.25
 * sm: 1.125rem:2.5rem = 2
 * md: 1.25rem:3rem = 2.4
 * lg: 1.5rem:3.5rem = 2.3

And here are the x-to-y padding ratios at each breakpoint:

* default: 20px:18px = 1.11
* sm: 24px:20px = 1.2
* md: 28px:24px = 1.66
* lg: 32px:28px = 1.14

My example is slightly contrived, but I think the point is correct: the ratios, the proportions, are changing at each breakpoint.

That's because at each breakpoint we're choosing different points along non-linear scales.

I think there are two possible solutions.

One is to do what I'm doing, which is to use the same point (e.g., `font-md`) on each non-linear scale at each breakpoint, and "scale the scales."

Another is to support a different scale for each breakpoint. From a config perspective that might look something like this:

```scss
    font-sizes: (
        default: (
            ...
            md: 1rem,
            lg: 1.25rem,
            ...
        ),
        sm: (
            ...
            md: 1.25rem,
            lg: 1.56rem,
            ...
        ),
        md: (
            ...
            md: 1.5rem,
            lg: 1.875rem,
            ...
        ),
        lg: (
            ...
            md: 1.75rem,
            lg: 2.19rem,
            ...
        ),
    )
```

That example doesn't match the way Uniform is actually configured, and I don't think you'd want to actually configure it that way, I'm just trying to illustrate a point: at each breakpoint the md-to-lg proportion (1.25x) is preserved. (The same would be true of the size scales: the ratio of each step at each breakpoint would be preserved.)

Some frameworks use the second approach and simplify config by asking users to choose a base value and a scale, and then let the framework do the calculations.

(For this kind of work, the golden ratio isn't a good fit, because the ratio is too large; major third (1.25), minor third (1.2), etc. are usually a better fit.)

Anyway, my point was that with the out of the box approach there are two challenges:

 * You have to match a t-shirt sized scale (for fonts) against some other semi-linear scale (for sizes) *at each breakpoint*. That takes some effort because the font and size scales weren't designed to scale together. (I didn't give an example of that, but the point is that they grow at different rates, and that makes them difficult to correlate.)

 * You have to choose different points along the scales at different breakpoints — and in doing so you change your proportions at each breakpoint. That seems unexpected.

For what it's worth, I think the simplest overall solution is:

 * Label all scales in rems, or in unitless t-shirt sizes.

 * Define all scales *directly* in rems — rather than converting pixels to rems using a hard-coded 16px base font size.

Again, if we're on the same page but disagree, no worries — I was able to find a good solution by turning the framework's documented knobs. I just want to make sure that we agree on what we disagree about.

It seems to me like anyone who creates a responsively scaling site will run into these same issues, but it's possible I'm just missing another way to think about it.

**Comment by michaellenaghan** [comment]
I took a quick look at Tailwind. They use a non-linear (t-shirt) font scale and a linear size scale.

The linear size scale uses a base of 0.25rem; the labels represent multiples of that value — e.g., `...-2` is 2 * 0.25rem. So:

```
      ...
      0.5: '0.125rem',
      1: '0.25rem',
      1.5: '0.375rem',
      2: '0.5rem',
      2.5: '0.625rem',
      ...
```

As you can see, there are half steps at the smaller end of the scale. At the upper end of the scale values are skipped over:

```
      ...
      80: '20rem',
      96: '24rem',
      ...
```

but the nice thing is that you can fill in any gaps you need without tossing out what they give you.

They point out that with their approach there's a linear relationship between labelled sizes; `...-8` is always twice as big as `...-4`, and always half as big as `...-16`.

Finally, Tailwind special cases not only 0px, but also 1px — a useful idea. Because `...-1` means "one of the base unit" they call the 1px value "px":

```
      ...
      px: '1px',
      0: '0',
      0.5: '0.125rem',
      1: '0.25rem',
      ...
```

Looking at the examples they give, Tailwind runs into the same problems I demonstrated in this thread: proportions will change at different breakpoints. At least, they will for fonts; you can choose proportion-preserving *sizes* at different breakpoints if you like. (That might require filling in some missing sizes.)

===

That aside, I thought I'd give an example of a framework that takes a different approach.

[Teutonic CSS](https://teutonic.co) — a framework with many nice ideas — has a [t-shirt sized space scale](https://teutonic.co/examples/theming#space-scale) and a [t-shirt sized type scale](https://teutonic.co/examples/theming#type-scale).

Teutonic allows users to choose both the base value (e.g., 0.25rem) and the ratio (e.g., 1.25). You can use any numeric value for the scale, but Teutonic [pre-defines variables for many well-known scales](https://github.com/fortrabbit/teutonic-css/blob/master/includes/_modular-scale-presets.scss); you can set the ratio to, say, `$major-third` or `$minor-third`.

The way Teutonic calculates the scale is simple and (I think) rather clever. It's obvious when you see it, but I think it would have taken me a bit of thinking to come up with it. :-) [Here](https://github.com/fortrabbit/teutonic-css/blob/master/includes/_vars-space-scale.scss) is the definition of the space scale, and [here](https://github.com/fortrabbit/teutonic-css/blob/master/includes/_vars-type-scale.scss) is the definition of the type scale.

Teutonic defines (optionally) a [unique scale per breakpoint](https://github.com/fortrabbit/teutonic-css/blob/master/includes/_text-size-all.scss), avoiding the changing proportions at different breakpoints. (Actually, that isn't entirely accurate. They're really modifiers that scale-the-scale; you could use both the large and medium scales on the same page. But you could *also* use them at different breakpoints.)

Apart from those things, Teutonic also supports a completely fluid scale, along the lines of the Bootstrap RFS system I linked to earlier. It's defined [here](https://github.com/fortrabbit/teutonic-css/blob/master/includes/_fluid-scale.scss). But I think it isn't documented. And there's a comment that might explain why. :-)
