### ISSUE TITLE
Add `max-width` media query breakpoint configuration option

### ISSUE THREAD

**Issue by ghost** [ThinkUniform/uniformcss#40]
Awesome project! :) Would love to see an option to enable `max-width` media queries for desktop-first design.

**Comment by jinsupark** [comment]
Hi there! Unfortunately a desktop-first design would break a lot of fundamental design of this project 😕. We had to pick between the two and currently the mobile first was more common so we opted for that design.

**Comment by ghost** [comment]
@jinsupark Thanks for letting me know. I'll close this ticket.
