### ISSUE TITLE
CDN link on documentation website not working

### ISSUE THREAD

**Issue by nelsonmic** [ThinkUniform/uniformcss#8]
**Describe the bug**
The CDN link on the documentation doesn't seem to be working, can you update the CDN link to be the same as the one on the code playground on [codepen](https://codepen.io/UniformCSS/pen/poNNqaE)

**To Reproduce**
you'll find the error [here](https://uniformcss.com/docs/installation/), where it says installation via CDN

@jinsupark

**Comment by jinsupark** [comment]
Thank you @nelsonmic, link has been updated.
