### ISSUE TITLE
Documentation link broken 

### ISSUE THREAD

**Issue by nelsonmic** [ThinkUniform/uniformcss#9]
**Describe the bug**
On the API reference, there is a broken link, it makes it difficult to search for that particular property.

**To Reproduce**
1. Go to '[uniformcss.com](https://uniformcss.com/)'
2. Click on read the docs.'
3. Click on API reference
4. Scroll down to 'top (position property)'
5. See error (broken link)

**Expected behavior**
On search, it's supposed to take me to the "top" section of the API reference, or on-click of the "top" link it should display the details, but it doesn't

@jinsupark

**Comment by jinsupark** [comment]
Thanks! This is now fixed.
